postgres:
  image: postgres
  volumes:
    - /data/main/postgres:/var/lib/postgresql/data
  env_file: ../.env

django:
  build: .
  user: django
  links:
    - postgres
    - redis
  command: /gunicorn.sh
  env_file: ../.env

nginx:
  build: ./compose/nginx
  links:
    - django
  ports:
    - "0.0.0.0:80:80"

redis:
  image: redis

celeryworker:
  build: .
  user: django
  env_file: ../.env
  links:
   - postgres
   - redis
  command: celery -A main.taskapp worker -l INFO

celerybeat:
  build: .
  user: django
  env_file: ../.env
  links:
    - postgres
    - redis
  command: celery -A main.taskapp beat -l INFO